name: Build Standard Library on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Remove Windows OpenSSH and use the default ssh in git
        run: Remove-WindowsCapability -Online -Name OpenSSH.Client
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RADARSIMCPP }}
          submodules: recursive
      - name: Build RadarSimLib
        run: |
          cd radarsimlib
          .\build_win.bat --arch cpu --tier standard
      # - name: Archive built module
      #   uses: actions/upload-artifact@v4
      #   if: success()
      #   with:
      #     name: radarsimlib_win_x86_64_cpu
      #     path: .\radarsimlib_win_x86_64_cpu
