name: Build Freetier Library on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Remove Windows OpenSSH and use the default ssh in git
        run: Remove-WindowsCapability -Online -Name OpenSSH.Client
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RADARSIMCPP }}
          submodules: recursive
      - name: Build RadarSimM
        run: |
          .\build_win.bat --arch cpu --tier free
      - name: Archive built module
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: radarsimm_win_x86_64_cpu_free
          path: .\radarsimm_win_x86_64_cpu_free
